// List of api routes
// Single source of truth for api endpoints

export const API = {
 AUTH:{
    REGISTER: '/api/auth/register',
    LOGIN: '/api/auth/login',
    LOGOUT: '/api/auth/logout',
    WHOAMI: '/api/auth/whoami',
    UPDATEPROFILE: '/api/auth/update-profile',
    CREATEUSER: '/api/auth/user',
    REQUEST_PASSWORD_RESET: '/api/auth/request-password-reset',
    RESET_PASSWORD: (token: string) => `/api/auth/reset-password/${token}`,
 },
 ADMIN:{
    USER: {
          CREATE: '/api/admin/users',
          GET_ALL: '/api/admin/users',
          GET_BY_ID: (id: string) => `/api/admin/users/${id}`,
          UPDATE: (id: string) => `/api/admin/users/${id}`,
          DELETE: (id: string) => `/api/admin/users/${id}`,
    },
    PET: {
        CREATE: '/api/admin/pet',
        GET_ALL: '/api/admin/pet',
        GET_BY_ID: (id: string) => `/api/admin/pet/${id}`,
        UPDATE: (id: string) => `/api/admin/pet/${id}`,
        DELETE: (id: string) => `/api/admin/pet/${id}`,
    },
    PROVIDER: {
        CREATE: '/api/admin/provider',
        GET_ALL: '/api/admin/provider',
        GET_BY_ID: (id: string) => `/api/admin/provider/${id}`,
        UPDATE: (id: string) => `/api/admin/provider/${id}`,
        DELETE: (id: string) => `/api/admin/provider/${id}`,
    },
    STATS: {
        DASHBOARD: '/api/admin/stats/dashboard',
    },
    BOOKING: {
        CREATE: '/api/admin/booking',
        GET_ALL: '/api/admin/booking',
        GET_BY_ID: (id: string) => `/api/admin/booking/${id}`,
        UPDATE: (id: string) => `/api/admin/booking/${id}`,
        DELETE: (id: string) => `/api/admin/booking/${id}`,
    },
    SERVICE: {
        CREATE: '/api/admin/service',
        GET_ALL: '/api/admin/service',
        GET_BY_ID: (id: string) => `/api/admin/service/${id}`,
        UPDATE: (id: string) => `/api/admin/service/${id}`,
        DELETE: (id: string) => `/api/admin/service/${id}`,
    },
    REVIEW: {
        GET_ALL: '/api/admin/review',
        GET_BY_ID: (id: string) => `/api/admin/review/${id}`,
        DELETE: (id: string) => `/api/admin/review/${id}`,
    },
    MESSAGE: {
        GET_ALL: '/api/admin/message',
        GET_BY_ID: (id: string) => `/api/admin/message/${id}`,
        DELETE: (id: string) => `/api/admin/message/${id}`,
    },
    HEALTH_RECORD: {
        GET_ALL: '/api/admin/health-record',
        GET_BY_ID: (id: string) => `/api/admin/health-record/${id}`,
        DELETE: (id: string) => `/api/admin/health-record/${id}`,
    },
    FEEDBACK: {
        GET_ALL: '/api/admin/feedback',
        GET_BY_PROVIDER: (providerId: string) => `/api/admin/feedback/provider/${providerId}`,
        GET_BY_ID: (id: string) => `/api/admin/feedback/${id}`,
        DELETE: (id: string) => `/api/admin/feedback/${id}`,
    },
    INVENTORY: {
        GET_ALL: '/api/admin/inventory',
        GET_BY_PROVIDER: (providerId: string) => `/api/admin/inventory/provider/${providerId}`,
        GET_BY_ID: (id: string) => `/api/admin/inventory/${id}`,
        DELETE: (id: string) => `/api/admin/inventory/${id}`,
    },
    ORDER: {
        GET_ALL: '/api/admin/order',
        GET_BY_ID: (id: string) => `/api/admin/order/${id}`,
        UPDATE: (id: string) => `/api/admin/order/${id}`,
        DELETE: (id: string) => `/api/admin/order/${id}`,
    },
    POST: {
        GET_ALL: '/api/admin/post',
        GET_BY_ID: (id: string) => `/api/admin/post/${id}`,
        DELETE: (id: string) => `/api/admin/post/${id}`,
    },
 },
 USER:{
    PET: {
        CREATE: '/api/user/pet',
        GET_ALL: '/api/user/pet',
        GET_BY_ID: (id: string) => `/api/user/pet/${id}`,
        UPDATE: (id: string) => `/api/user/pet/${id}`,
        DELETE: (id: string) => `/api/user/pet/${id}`,
    },
 },
 BOOKING: {
    CREATE: '/api/booking',
    GET_ALL: '/api/booking',
    GET_BY_ID: (id: string) => `/api/booking/${id}`,
    UPDATE: (id: string) => `/api/booking/${id}`,
    DELETE: (id: string) => `/api/booking/${id}`,
    GET_BY_USER: (userId: string) => `/api/booking/user/${userId}`,
 },
 SERVICE: {
    GET_ALL: '/api/service',
    GET_BY_ID: (id: string) => `/api/service/${id}`,
    GET_BY_PROVIDER: (providerId: string) => `/api/service/provider/${providerId}`,
 },
 REVIEW: {
    CREATE: '/api/review',
    GET_MY: '/api/review/my',
    GET_BY_ID: (id: string) => `/api/review/${id}`,
    UPDATE: (id: string) => `/api/review/${id}`,
    DELETE: (id: string) => `/api/review/${id}`,
    GET_BY_PROVIDER: (providerId: string) => `/api/review/provider/${providerId}`,
    GET_BY_PRODUCT: (productId: string) => `/api/review/product/${productId}`,
    GET_PROVIDER_RATING: (providerId: string) => `/api/review/provider/${providerId}/rating`,
 },
 MESSAGE: {
    CREATE: '/api/message',
    GET_MY: '/api/message/my',
    GET_BY_ID: (id: string) => `/api/message/${id}`,
    UPDATE: (id: string) => `/api/message/${id}`,
    DELETE: (id: string) => `/api/message/${id}`,
 },
 HEALTH_RECORD: {
    CREATE: '/api/health-record',
    GET_BY_PET: (petId: string) => `/api/health-record/pet/${petId}`,
    GET_BY_ID: (id: string) => `/api/health-record/${id}`,
    UPDATE: (id: string) => `/api/health-record/${id}`,
    DELETE: (id: string) => `/api/health-record/${id}`,
 },
 ATTACHMENT: {
    CREATE: '/api/attachment',
    GET_BY_HEALTH_RECORD: (healthRecordId: string) => `/api/attachment/health-record/${healthRecordId}`,
    GET_BY_ID: (id: string) => `/api/attachment/${id}`,
    UPDATE: (id: string) => `/api/attachment/${id}`,
    DELETE: (id: string) => `/api/attachment/${id}`,
 },
 PROVIDER: {
    REGISTER: '/api/provider/register',
    LOGIN: '/api/provider/login',
    GET_ALL: '/api/provider',
    GET_BY_ID: (id: string) => `/api/provider/${id}`,
    UPDATE: (id: string) => `/api/provider/${id}`,
    DELETE: (id: string) => `/api/provider/${id}`,
    SET_TYPE: '/api/provider/set-type',
    APPROVE: (id: string) => `/api/provider/approve/${id}`,
    REJECT: (id: string) => `/api/provider/reject/${id}`,
    GET_BY_STATUS: (status: string) => `/api/provider/status/${status}`,
    SERVICE: {
        CREATE: '/api/provider/service',
        GET_ALL: '/api/provider/service',
        GET_BY_ID: (id: string) => `/api/provider/service/${id}`,
        UPDATE: (id: string) => `/api/provider/service/${id}`,
        DELETE: (id: string) => `/api/provider/service/${id}`,
    },
    INVENTORY: {
        CREATE: '/api/provider/inventory',
        GET_BY_PROVIDER: (providerId: string) => `/api/provider/inventory/provider/${providerId}`,
        GET_BY_ID: (id: string) => `/api/provider/inventory/${id}`,
        UPDATE: (id: string) => `/api/provider/inventory/${id}`,
        DELETE: (id: string) => `/api/provider/inventory/${id}`,
    },
    FEEDBACK: {
        CREATE: '/api/feedback',
        GET_BY_PROVIDER: (providerId: string) => `/api/feedback/provider/${providerId}`,
        GET_BY_ID: (id: string) => `/api/feedback/${id}`,
        UPDATE: (id: string) => `/api/feedback/${id}`,
        DELETE: (id: string) => `/api/feedback/${id}`,
    },
    BOOKING: {
        GET_MY: '/api/provider/booking/my',
        UPDATE_STATUS: (id: string) => `/api/provider/booking/${id}/status`,
        GET_BY_ID: (id: string) => `/api/provider/booking/${id}`,
    },
    POST: {
        CREATE: '/api/provider/post',
        GET_MY: '/api/provider/post/my',
        UPDATE: (id: string) => `/api/provider/post/${id}`,
        DELETE: (id: string) => `/api/provider/post/${id}`,
    },
 },
 ORDER: {
    CREATE: '/api/order',
    GET_MY: '/api/order/my',
    GET_BY_ID: (id: string) => `/api/order/${id}`,
    UPDATE: (id: string) => `/api/order/${id}`,
    DELETE: (id: string) => `/api/order/${id}`,
 },
 POST: {
    GET_ALL: '/api/post',
    GET_BY_ID: (id: string) => `/api/post/${id}`,
    GET_BY_PROVIDER: (providerId: string) => `/api/post/provider/${providerId}`,
 },
 PRODUCT: {
    GET_ALL: '/api/product',
    GET_BY_ID: (id: string) => `/api/product/${id}`,
    GET_BY_PROVIDER: (providerId: string) => `/api/product/provider/${providerId}`,
 },
};