// List of api routes
// Single source of truth for api endpoints

export const API = {
 AUTH:{
    REGISTER: '/api/auth/register',
    LOGIN: '/api/auth/login',
    LOGOUT: '/api/auth/logout',
    WHOAMI: '/api/auth/whoami',
    UPDATEPROFILE: '/api/auth/update-profile',
    CREATEUSER: '/api/auth/user',
    REQUEST_PASSWORD_RESET: '/api/auth/request-password-reset',
    RESET_PASSWORD: (data: any) => `/api/auth/reset-password/${data}`,
 },
 ADMIN:{
    USER: {
          CREATE: '/api/admin/users',
          GET_ALL: '/api/admin/users',
          GET_BY_ID: (data: any) => `/api/admin/users/${data}`,
          UPDATE: (data: any) => `/api/admin/users/${data}`,
          DELETE: (data: any) => `/api/admin/users/${data}`,
    },
    PET: {
        CREATE: '/api/admin/pet',
        GET_ALL: '/api/admin/pet',
        GET_BY_ID: (data: any) => `/api/admin/pet/${data}`,
        UPDATE: (data: any) => `/api/admin/pet/${data}`,
        DELETE: (data: any) => `/api/admin/pet/${data}`,
    },
    PROVIDER: {
        CREATE: '/api/admin/provider',
        GET_ALL: '/api/admin/provider',
        GET_BY_ID: (data: any) => `/api/admin/provider/${data}`,
        UPDATE: (data: any) => `/api/admin/provider/${data}`,
        DELETE: (data: any) => `/api/admin/provider/${data}`,
        SERVICE: {
            GET_ALL: '/api/admin/provider-service',
            GET_BY_ID: (data: any) => `/api/admin/provider-service/${data}`,
            APPROVE: (data: any) => `/api/admin/provider-service/${data}/approve`,
            REJECT: (data: any) => `/api/admin/provider-service/${data}/reject`,
        },
    },
    STATS: {
        DASHBOARD: '/api/admin/stats/dashboard',
    },
    BOOKING: {
        CREATE: '/api/admin/booking',
        GET_ALL: '/api/admin/booking',
        GET_BY_ID: (data: any) => `/api/admin/booking/${data}`,
        UPDATE: (data: any) => `/api/admin/booking/${data}`,
        DELETE: (data: any) => `/api/admin/booking/${data}`,
    },
    SERVICE: {
        CREATE: '/api/admin/service',
        GET_ALL: '/api/admin/service',
        GET_BY_ID: (data: any) => `/api/admin/service/${data}`,
        UPDATE: (data: any) => `/api/admin/service/${data}`,
        DELETE: (data: any) => `/api/admin/service/${data}`,
    },
    REVIEW: {
        GET_ALL: '/api/admin/review',
        GET_BY_ID: (data: any) => `/api/admin/review/${data}`,
        DELETE: (data: any) => `/api/admin/review/${data}`,
    },
    MESSAGE: {
        GET_ALL: '/api/admin/message',
        GET_BY_ID: (data: any) => `/api/admin/message/${data}`,
        DELETE: (data: any) => `/api/admin/message/${data}`,
    },
    HEALTH_RECORD: {
        GET_ALL: '/api/admin/health-record',
        GET_BY_ID: (data: any) => `/api/admin/health-record/${data}`,
        DELETE: (data: any) => `/api/admin/health-record/${data}`,
    },
    FEEDBACK: {
        GET_ALL: '/api/admin/feedback',
        GET_BY_PROVIDER: (data: any) => `/api/admin/feedback/provider/${data}`,
        GET_BY_ID: (data: any) => `/api/admin/feedback/${data}`,
        DELETE: (data: any) => `/api/admin/feedback/${data}`,
    },
    INVENTORY: {
        GET_ALL: '/api/admin/inventory',
        GET_BY_PROVIDER: (data: any) => `/api/admin/inventory/provider/${data}`,
        GET_BY_ID: (data: any) => `/api/admin/inventory/${data}`,
        DELETE: (data: any) => `/api/admin/inventory/${data}`,
    },
    ORDER: {
        GET_ALL: '/api/admin/order',
        GET_BY_ID: (data: any) => `/api/admin/order/${data}`,
        UPDATE: (data: any) => `/api/admin/order/${data}`,
        DELETE: (data: any) => `/api/admin/order/${data}`,
    },
    POST: {
        GET_ALL: '/api/admin/post',
        GET_BY_ID: (data: any) => `/api/admin/post/${data}`,
        DELETE: (data: any) => `/api/admin/post/${data}`,
    },
 },
 USER:{
    PET: {
        CREATE: '/api/user/pet',
        GET_ALL: '/api/user/pet',
        GET_BY_ID: (data: any) => `/api/user/pet/${data}`,
        UPDATE: (data: any) => `/api/user/pet/${data}`,
        DELETE: (data: any) => `/api/user/pet/${data}`,
    },
 },
 BOOKING: {
    CREATE: '/api/booking',
    GET_ALL: '/api/booking',
    GET_BY_ID: (data: any) => `/api/booking/${data}`,
    UPDATE: (data: any) => `/api/booking/${data}`,
    DELETE: (data: any) => `/api/booking/${data}`,
    GET_BY_USER: (data: any) => `/api/booking/user/${data}`,
 },
 SERVICE: {
    GET_ALL: '/api/service',
    GET_BY_ID: (data: any) => `/api/service/${data}`,
    GET_BY_PROVIDER: (data: any) => `/api/service/provider/${data}`,
 },
 REVIEW: {
    CREATE: '/api/review',
    GET_MY: '/api/review/my',
    GET_BY_ID: (data: any) => `/api/review/${data}`,
    UPDATE: (data: any) => `/api/review/${data}`,
    DELETE: (data: any) => `/api/review/${data}`,
    GET_BY_PROVIDER: (data: any) => `/api/review/provider/${data}`,
    GET_BY_PRODUCT: (data: any) => `/api/review/product/${data}`,
    GET_PROVIDER_RATING: (data: any) => `/api/review/provider/${data}/rating`,
 },
 MESSAGE: {
    CREATE: '/api/message',
    GET_ALL: '/api/message',
    GET_MY: '/api/message/my',
    GET_BY_ID: (data: any) => `/api/message/${data}`,
    UPDATE: (data: any) => `/api/message/${data}`,
    DELETE: (data: any) => `/api/message/${data}`,
 },
 HEALTH_RECORD: {
    CREATE: '/api/health-record',
    GET_BY_PET: (data: any) => `/api/health-record/pet/${data}`,
    GET_BY_ID: (data: any) => `/api/health-record/${data}`,
    UPDATE: (data: any) => `/api/health-record/${data}`,
    DELETE: (data: any) => `/api/health-record/${data}`,
 },
 ATTACHMENT: {
    CREATE: '/api/attachment',
    GET_BY_HEALTH_RECORD: (data: any) => `/api/attachment/health-record/${data}`,
    GET_BY_ID: (data: any) => `/api/attachment/${data}`,
    UPDATE: (data: any) => `/api/attachment/${data}`,
    DELETE: (data: any) => `/api/attachment/${data}`,
 },
 PROVIDER: {
    REGISTER: '/api/provider/register',
    LOGIN: '/api/provider/login',
    GET_ALL: '/api/provider',
    GET_BY_ID: (data: any) => `/api/provider/${data}`,
    UPDATE: (data: any) => `/api/provider/${data}`,
    DELETE: (data: any) => `/api/provider/${data}`,
    SET_TYPE: '/api/provider/set-type',
    APPROVE: (data: any) => `/api/provider/approve/${data}`,
    REJECT: (data: any) => `/api/provider/reject/${data}`,
    GET_BY_STATUS: (data: any) => `/api/provider/status/${data}`,
    SERVICE: {
        CREATE: '/api/provider/service',
        GET_ALL: '/api/provider/service',
        GET_BY_ID: (data: any) => `/api/provider/service/${data}`,
        UPDATE: (data: any) => `/api/provider/service/${data}`,
        DELETE: (data: any) => `/api/provider/service/${data}`,
    },
    INVENTORY: {
        CREATE: '/api/provider/inventory',
        GET_BY_PROVIDER: (data: any) => `/api/provider/inventory/provider/${data}`,
        GET_BY_ID: (data: any) => `/api/provider/inventory/${data}`,
        UPDATE: (data: any) => `/api/provider/inventory/${data}`,
        DELETE: (data: any) => `/api/provider/inventory/${data}`,
    },
    FEEDBACK: {
        CREATE: '/api/feedback',
        GET_BY_PROVIDER: (data: any) => `/api/feedback/provider/${data}`,
        GET_BY_ID: (data: any) => `/api/feedback/${data}`,
        UPDATE: (data: any) => `/api/feedback/${data}`,
        DELETE: (data: any) => `/api/feedback/${data}`,
    },
    BOOKING: {
        GET_MY: '/api/provider/booking/my',
        UPDATE_STATUS: (data: any) => `/api/provider/booking/${data}/status`,
        GET_BY_ID: (data: any) => `/api/provider/booking/${data}`,
    },
    POST: {
        CREATE: '/api/provider/post',
        GET_MY: '/api/provider/post/my',
        UPDATE: (data: any) => `/api/provider/post/${data}`,
        DELETE: (data: any) => `/api/provider/post/${data}`,
    },
 },
 ORDER: {
    CREATE: '/api/order',
    GET_MY: '/api/order/my',
    GET_BY_ID: (data: any) => `/api/order/${data}`,
    UPDATE: (data: any) => `/api/order/${data}`,
    DELETE: (data: any) => `/api/order/${data}`,
 },
 POST: {
    GET_ALL: '/api/post',
    GET_BY_ID: (data: any) => `/api/post/${data}`,
    GET_BY_PROVIDER: (data: any) => `/api/post/provider/${data}`,
 },
 PRODUCT: {
    GET_ALL: '/api/product',
    GET_BY_ID: (data: any) => `/api/product/${data}`,
    GET_BY_PROVIDER: (data: any) => `/api/product/provider/${data}`,
 },
 CART: {
    GET_MY: '/api/cart',
    ADD_ITEM: '/api/cart/add',
    UPDATE_ITEM: (data: any) => `/api/cart/item/${data}`,
    REMOVE_ITEM: (data: any) => `/api/cart/item/${data}`,
    CLEAR: '/api/cart',
 },
};


